openapi: "3.0.0"
info:
  title: AuthentiCare Bank
  description: "Authenticare banking cares for your authentic experience!"
  termsOfService: https://authenticare-bank.com/terms
  contact:
    email: randakar@gmail.com
  license:
    name: The GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: ${version}
externalDocs:
  description: Find this on github!
  url: https://github.com/randakar/AuthentiCareBankApi
tags:
  - name: account
    description: Operations on accounts
  - name: customer
    description: Operations on customers
  - name: transaction
    description: Money transfer
paths:
  /customer/me:
    get:
      tags:
        - customer
      summary: Get my own customer details
      operationId: getCurrentCustomer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: User not found
          content: { }
  /customer/{id}:
    get:
      tags:
        - customer
      summary: Get customer by id
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          description: 'The id of the customer that needs to be fetched. '
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: User not found
          content: { }
components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstname
        - lastname
        - email
        - accountIds
      properties:
        id:
          type: integer
          format: int64
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string