openapi: 3.0.0
info:
  contact:
    email: randakar@gmail.com
  description: Authenticare banking cares for your authentic experience!
  license:
    name: The GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  termsOfService: https://authenticare-bank.com/terms
  title: AuthentiCare Bank
  version: 0.0.1
externalDocs:
  description: Find this on github!
  url: https://github.com/randakar/AuthentiCareBankApi
servers:
  - url: http://localhost:8080/
  - url: /
security:
  - BasicAuth: []
tags:
  - description: Operations on accounts
    name: account
  - description: Operations on customers
    name: customer
  - description: Money transfer
    name: transaction
paths:

  /customer/me:
    get:
      operationId: getCurrentCustomer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerViewModel'
          description: successful operation
        404:
          content: {}
          description: Customer not found
      summary: Get my own customer details
      tags:
        - customer
      x-accepts: application/json

  /customer/{id}:
    get:
      operationId: getCustomerById
      parameters:
        - description: 'The id of the customer that needs to be fetched. '
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: integer
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerViewModel'
          description: Customer view model retrieved
        404:
          content: {}
          description: Customer not found
      summary: Get customer by id
      tags:
        - customer
      x-accepts: application/json

  /customer/{id}/accounts:
    get:
      operationId: getCustomerAccounts
      parameters:
        - description: 'The id of the customer that accounts need to be fetched for'
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: integer
          style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountViewModel'
          description: successful operation
        404:
          content: {}
          description: Customer not found
      summary: Get customer by id
      tags:
        - customer
      x-accepts: application/json

  /customer:
    post:
      operationId: createCustomer
      summary: Create a new customer.
      description: Create a new customer.
      requestBody:
        description: Customer
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerModel'
      responses:
        200:
          description: Customer created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerViewModel'
        409:
          description: Customer already exists.
      x-accepts: application/json
      tags:
        - customer

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:

    currencyCode:
      type: string
      description: 3 letter currency code as defined by ISO-4217
      pattern: "[A-Z]{3}"
      format: iso-4217
      example: EUR

    iban:
      type: string
      pattern: '[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}'
      example: 'NL20INGB0001234567'

    cardtype:
        type: string
        pattern: (creditcard|debitcard)
        example: creditcard

    MoneyModel:
      type: object
      properties:
        amount:
          type: number
          description: Amount expressed as a decimal number of major currency units
          format: decimal
          minimum: 0
          example: 99.95
        currency:
          $ref: '#/components/schemas/currencyCode'
      required:
        - amount
        - currency

    CustomerModel:
      example:
        userName: Fooman
        email: email@rabobank.nl
        firstName: Fooman
        lastName: Barname
      properties:
        userName:
          type: string
          pattern: '[A-Z]{3,}'
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - userName
      type: object

    CustomerViewModel:
      allOf: # Complete view
        - $ref: '#/components/schemas/CustomerModel'
      example:
        id: 0
      properties:
        id:
          format: int64
          type: integer
      required:
        - id
        - userName

    CustomerOverviewModel:
      allOf: # Complete view
        - $ref: '#/components/schemas/CustomerViewModel'
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountViewModel'
        cards:
          type: array
          items:
            $ref: '#/components/schemas/CardModel'

    AccountModel:
      example:
        iban: 'NL20INGB0001234567'
        owner: 0
        name: "DeBetaalRekening"
        description: 'Mijn Eerste Rekening!'
      properties:
        iban:
          $ref: '#/components/schemas/iban'
        owner:
          format: int64
          type: integer
        name:
          type: string
        description:
          type: string
        balance:
          $ref: '#/components/schemas/MoneyModel'
      required:
        - iban
        - owner

    AccountViewModel:
      allOf: # Complete view
        - $ref: '#/components/schemas/AccountModel'
      example:
        id: 0
      properties:
        id:
          format: int64
          type: integer
        owners:
          type: array
          items:
            type: number
            format: int64
      required:
        - id

    AccountOverviewModel:
      allOf: # Complete view
        - $ref: '#/components/schemas/AccountViewModel'
      properties:
        owners:
          type: array
          items:
            $ref: '#/components/schemas/CustomerViewModel'
        cards:
          type: array
          items:
            $ref: '#/components/schemas/CardModel'

    CardModel:
      discriminator:
        propertyName: cardType
        mapping:
          creditcard: '#/components/schemas/CreditCardModel'
          debitcard:  '#/components/schemas/DebitCardModel'
      properties:
        description:
          type: string
          example: "Huishouden"
        status:
          type: string
          pattern: (ACTIVE|BLOCKED|EXPIRED)
          description: current state of the card
        customerId:
          type: number
          format: int64
        cardType:
          $ref: '#/components/schemas/cardtype'
        expirationDate:
          type: string
          format: date
        issuer:
          description: Company issuing the card
          type: string
          example: Visa

    CreditCardModel:
      allOf:
        - $ref: '#/components/schemas/CardModel'
        - type: object
          description: CreditCard
          properties:
            cardNumber:
              type: string
              ## format: https://stackoverflow.com/questions/9315647/regex-credit-card-number-tests - holy cow ..
            cardHolder:
              description: Card holder
              type: string
              example: KRAMER
            securityCode:
              description: CVV
              type: string
              format: '[0-9]{3}'
              example: 656

    DebitCardModel:
      allOf:
        - $ref: '#/components/schemas/CardModel'
        - type: object
          description: DebitCard
          properties:
            cardNumber:
              type: string

    TransactionModel:
      properties:
        timestamp:
          type: string
          format: date-time
        from:
          $ref: '#/components/schemas/iban'
        to:
          $ref: '#/components/schemas/iban'
        amount:
          $ref: '#/components/schemas/MoneyModel'
        description:
          type: string
        authorization:
          type: string
        cardType:
          $ref: '#/components/schemas/cardtype'
      required:
        - from
        - to
        - amount
        - authorization

    TransactionViewModel:
      allOf: # Complete view
        - $ref: '#/components/schemas/AccountModel'
      properties:
        id:
          format: int64
          type: integer

    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
        - code
        - message
      type: object
