spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create

